name: Docker Hub Publish

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker build -t your-docker-hub-username/image-name:latest .
        docker push your-docker-hub-username/image-name:latest
