name: Docker Hub Publish

on:
  push:
    branches:
      - main 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker build -t danipoletto/laravel-project:1 .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker push danipoletto/laravel-project:latest
