name: Docker Hub Publish

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:

    - name: Build and push Docker image
      run: |
        docker build -t danipoletto/laravel-project:latest -f laravel-project.Dockerfile
        docker push danipoletto/laravel-project:latest
